### PR TITLE
Various visual improvements

### PR DESCRIPTION
**Pull request by mmicko**
- Added Tags tree, in which mutations are grouped per tag (one mutation can be in multiple lists)
- When source location is selected we select line but also highlight specified text block
- Display mutation information/explanation in status bar
- Clear properties when selection change on forgotten places.

### CODE REVIEW

**Comment by nakengelhardt** [comment]
Works well! (tested on mac) Some small points:

- I think the "All Tags" list item is not necessary, as it has the same contents as the mutations tab (also, the name is very slightly wrong as it will also include mutations with no tags). However, if (and only if) there are any mutations that were not tagged with anything, there should be a "No Tags" list item for them, as it can be an important sign that there is something wrong (e.g. did not finish mcy run).

- Clicking on a mutation in the tags tab maybe could also jump to corresponding line, even if it doesn't show line information in the list directly.

- I'm not sure about the location of the descriptive text for the mutation in the status bar. It took me a long time to notice where it was, and if the window is too small, important information will be cut off. Would it be difficult to add this as another line to the property window, but with text wrap?

- This one is probably a QT bug and not anything important, but I just noticed the tab padding width changes when selected:
  Screenshot 2020-10-07 at 15 22 39
  Screenshot 2020-10-07 at 15 22 31

**Comment by mmicko** [comment]
1. Agree with first point, that should be possible to add.
2. To make clicking on mutation select line, I could jump to first source location, but can highlight all source lines selections. Would this be fine ?
3. Can add this to property window, will experiment there a bit to make it more visible. We can later discuss if it makes sense to keep info on both places. On Linux and Windows status bar is quite visible, to be honest did not check under macOS.
4. Believe that is how control is handled under macOS, no custom code for handling tabs so guess that is not possible to alter.

**Comment by nakengelhardt** [comment]
2: From experience, last location is actually the most interesting one, first location is often just the variable declaration. It's a bit unintuitive, but in practice I think last location would be more useful...

**Comment by mmicko** [comment]
@nakengelhardt can you please take a look, this should conclude changes we agreed to implement.

**Comment by nakengelhardt** [comment]
LGTM. No chance of missing the description now, it's the brightest thing on the screen 😅
The line with the "in module... cell..." now no longer wraps to the window size, it requires hover and wait for tooltip to read. Is that intentional?

**Pull request merged**
